### ISSUE TITLE
Add workflows for gutenberg blocks

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-lib-tasks#3]
babel / webpack / esnext / jsx etc...

**Comment by AndreaBarghigiani** [comment]
I am experimenting with Gutenberg started by studying the course of Zac Gordon and found simple and useful at the same time its [starter repository](https://github.com/zgordon/how-to-gutenberg-plugin).

I know there are some other ways to start a Gutenberg plugin like [create-guten-block](https://github.com/ahmadawais/create-guten-block) but I think it is simplyer customize the code from the first one.

Can I help you up with something?

**Comment by thomasplevy** [comment]
@AndreaBarghigiani yes! Of course

If I'm being really honest I kind of want to work on this myself so I ensure that I fully understand it but if you can figure it all out and integrate it into the current lib contribute away. I'd be stoked to have it solved as it's currently looking like I wont get some availability for this for at least another week or so.

Thanks

**Comment by actual-saurabh** [comment]
I feel the most reasonable way to go about it would be to use Webpack for the bunding and build process for Gutenberg to start off with and keep Gulp for running static file related tasks and such. They can be used together instead of choosing one or the other, at least at the beginning. Gradually, we can move everything over to Webpack unless there are tasks that can't be easily migrated.

See:
- https://css-tricks.com/combine-webpack-gulp-4/
- https://pawelgrzybek.com/using-webpack-with-gulpjs/

So, we could start working on a Gutenberg specific workflow without worrying about the existing build process is my best thought.

**Comment by AndreaBarghigiani** [comment]
I think that you idea @actual-saurabh is perfect and will let even unexperienced developer like miself to simply follow the settings in the [starter repository](https://github.com/zgordon/how-to-gutenberg-plugin) and add them into your workflow and start building some blocks.

**Comment by thomasplevy** [comment]
@AndreaBarghigiani I'd love to do a webinar about the workflow. It is advanced but if we're being really honest it's a basic gulp workflow with a configuration file. I realize it's dense and requires more documentation and I'll be adding it in the future. We'll get this clearer as we move forward. At this very moment I can't promise I'll have something built out to really document this in time to get PRs in for Hacktoberfest. And, since Gutenberg is fast approaching it may prove simpler for me to build it out so we can get our core Gutenberg features in. Please don't wait for me if you have a need to really get started on this today. I'd love to have it in but I really truly do not have the capacity to build a framework and teach the workflow before Gutenberg is released. My apologies.

**Comment by thomasplevy** [comment]
@AndreaBarghigiani development of blocks will be offloaded to a completely separate plugin specifically built for block development: https://github.com/gocodebox/lifterlms-blocks/

This plugin will be loaded as part of the LifterLMS core for the 5.0 release: https://github.com/gocodebox/lifterlms/issues/701
