### ISSUE TITLE
Sourcemaps should not be inlined

### ISSUE THREAD

**Issue by pjeby** [gocodebox/lifterlms-lib-tasks#8]
While debugging performance issues on a site with LifterLMS, the Google PageSpeed Insights tool claimed that LifterLMS's CSS and JS should be minified...  despite those files being the minified versions.

On inspection, this is because the bulk of the size of the "minified" CSS and JS comes from the embedded sourcemaps in those files.  The tasks to generate them are not passing the necessary argument to `maps.write()` to write the sourcemap to a separate file.  Because of this, the CSS and JS files are *much* bigger than they need to be: Google's estimates suggest that about 2/3 of the LLMS CSS file size and 80% of the JavaScript is wasted on the embedded sourcemaps -- possibly more depending on compression.

With the correct settings, the sourcemaps would be written to a separate `.map` file that would only be loaded when using a browser's development tools, instead of being loaded in every browser every time.

**Comment by thomasplevy** [comment]
@pjeby 
Thanks for the heads up. If you have the time a PR would be greatly appreciated since it seems you already have pinpointed the issue.

Thanks

**Comment by eri-trabiccolo** [comment]
reported also on
HS-112995

**Comment by eri-trabiccolo** [comment]
@thomasplevy if it helps I was trying something here:
https://github.com/gocodebox/lifterlms/blob/30cc2696f524ae1f1504d3ae2f422c4d0ced8ceb/gulpfile.js/tasks/js-additional.js#L25-L39
with:
```
	pump( [
		gulp.src( 'assets/js/private/**/*.js' ),
			include(),
			maps.init(),
			header( notice.join( '\n' ) ),
			maps.write( '/' ),
			gulp.dest( 'assets/js' ),
			gulpIgnore.exclude('**/*.map'),
			maps.init(),
			uglify(),
			rename( {
				suffix: '.min',
			} ),
			maps.write( '/' ),
			gulp.dest( 'assets/js' )
		],
		cb
	);
```
of course we need the gulp-ignore module and its deps + requiring it `gulpIgnore = require( 'gulp-ignore' )`.
I got caught on something else (support) and didn't test thoroughly (meaning that the map then actually works fine), but should work.

**Comment by thomasplevy** [comment]
@eri-trabiccolo I didn't realize you were working on this and I've been working on this since our meeting

I should have assigned it sorry!

I got the CSS figured out using `gulp-ignore` and will do the same on JS later today. I have to go to my appointment now.

**Comment by eri-trabiccolo** [comment]
@thomasplevy not your fault, I should've assigned it to me this morning (which means like 9-10hs ago!) but I didn't, I've just spent an hour or so this morning on this but I haven't finished it because there were some other pending issue I had to care about, and I felt I was not going that much forward :/
I should've probably shared my partial results earlier so that they might be helpful.

Have a great day.

**Comment by pjeby** [comment]
I'm kind of curious why you're ignoring the maps instead of just writing them to the same output directory.  Having them there means that you can view the source in production, but they're only sent to the browser if you open the dev console and look at source code.  (That functionality exists now, it's just that the map is sent immediately instead of just on-demand.)

(IOW, I would suggest writing the map files and including them in the distribution, as it is the least change from how things work now.  It's just that they'll be on-demand loaded from a separate file instead of proactively included on every request.)

**Comment by thomasplevy** [comment]
@pjeby my WIP does not ignore the maps

**Comment by pjeby** [comment]
Ah, looks I misread that bit.  I see now that it's just filtering the pre-minification maps, not the final ones.
